# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gIzu6Jo0vpjsfJUNXIcPVcOCnu3U8VQx
"""

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
pic1 = cv2.imread('nfs.png')
cv2_imshow(pic1)

pic1_wb = cv2.cvtColor(pic1, cv2.COLOR_BGR2GRAY)
cv2_imshow(pic1_wb)

pic2 = cv2.imread('Xin_Storm_Kaolin.jpg')
cv2_imshow(pic2)

pic2_wb = cv2.cvtColor(pic2, cv2.COLOR_BGR2GRAY)
cv2_imshow(pic2_wb)

pic3 = cv2.imread('hacker.jpg')
cv2_imshow(pic3)

pic3_wb = cv2.cvtColor(pic3, cv2.COLOR_BGR2GRAY)
cv2_imshow(pic3_wb)

pic4 = cv2.imread('iccup.jpg')
cv2_imshow(pic4)

pic4_wb = cv2.cvtColor(pic4, cv2.COLOR_BGR2GRAY)
cv2_imshow(pic4_wb)

pic5 = cv2.imread('phoenix.jpg')
cv2_imshow(pic5)

pic5_wb = cv2.cvtColor(pic5, cv2.COLOR_BGR2GRAY)
cv2_imshow(pic5_wb)